
version: 2.1
jobs:
  compile:
   machine:
      image: ubuntu-1604:201903-01 
   steps:
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison ccache
            git clone https://github.com/JamieHoSzeYui/mango414 --depth=1 --single-branch mango414
            cd mango414
            wget https://raw.githubusercontent.com/JamieHoSzeYui/mangobuildrrrr/master/build.sh
            chmod -R 0777 *
            ./build.sh

             
                         
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile